
version: 0.2

env:
  variables:
    BUCKET_NAME: "modelops-dev-mkdocs-bucket"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install mkdocs
      - pip install mkdocs-material
      - pip install mkdocs-jupyter
      - pip install mkdocs-swagger-ui-tag
      - pip install mkdocs-glightbox

  build:
    commands:
      - echo "Printing current working directory..."
      - pwd
      - echo "Listing files"
      - ls -R
      - echo "Building MkDocs site..."
      - pwd
      - mkdocs build
      - pwd

artifacts:
  files:
    - '**/*'
  base-directory: site
